spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

security:
  secret: my-secret

server:
  port: 8080